### ISSUE TITLE
Handle Expired Tokens

### ISSUE THREAD

**Issue by dproc96** [hatchways/team-yugioh#110]
Right now if you load the home page with an expired token you just see an empty version of the homepage, it should redirect to login

**Comment by alvyjudy** [comment]
Taras and I had discussed this issue before. We had the redirection set up but it wouldn't handle a page refresh properly. I decided to opt out of that for the demo lol. 

The simple fix is to add a redirection in our `<PrivateRoute/>` component, which checks for the `authenticated` flag from context but the problem this poses is that on page load, the `authenticated` is default to false, and it would causes the redirection before the app actually knows whether the user is authenticated (useEffect fires after redirection). 

I thought of a few solutions:
- we can default the `authentication` flag to true just for the UI display. Since important data won't show up without a real authentication, this won't pose any security issue. The UI will display just fine with but empty content, and when the result from `useEffect` comes back, the app either display the fetched content or do a redirection.
- We can use the history API to do a redirection when the route `/api/authentication/test` returns an error (redirect inside the catch block). I personally prefer this way because it is more modular and easier to test. 
- We can save the location of the page before redirection in the context and redirect the user back to it once authentication result comes back
