### ISSUE TITLE
Bug: log out button does not display properly after logging in

### ISSUE THREAD

**Issue by alvyjudy** [hatchways/team-yugioh#124]
Don't mind my sleep schedule but I found another bug lol )

After logging in, the user Icon on the top navigation bar does not display properly, nor does the log out menu show up.
<img width="704" alt="image" src="https://user-images.githubusercontent.com/53921639/106560320-d5ff2c80-64f4-11eb-9003-738db104feeb.png">

After a page refresh, they show up properly.
<img width="722" alt="image" src="https://user-images.githubusercontent.com/53921639/106560367-eca58380-64f4-11eb-8c34-67f556682bae.png">

I suspect the issue is because the `src/components/GoogleLoginButton.js` did not update the context properly.

**Comment by kozaktar** [comment]
This happens because the app request user data before the authentication token is received from the server:

GET /api/authentication/test 401 0.626 ms - 44
**GET /api/user/data 401 0.476 ms - 44**
POST /api/authentication/google 201 339.849 ms - 280
GET /api/authentication/test 304 1.492 ms - -

This can be fixed by global loading state
